### ISSUE TITLE
Determine if/how FPC(s) will reported or evaluated

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#12]

**Comment by mraccess77** [comment]
While the Access Board has said that FPC only apply when equivalent facilitation is used or when there is not a standard to address the functionality -- some might find the mapping to FPC useful to understand what categories of users an issue impacts.  In addition, when equivalent facilitation is used - showing these mappings will give testers of the FPC an idea of the types of things that the FPC apply to.   So it may be helpful to map them but indicate they are there for this reason and not for determining conformance to the technical standards.  This is tricky because the W3C considers WCAG as functional standards because they are technology neutral and don't require specific technologies or techniques as long as the SC is met.

**Comment by drewnielson** [comment]
Addressing within reporting structure of the Accessibility Conformance Reporting Tool (ACRT) under development. To replace previous reporting functionality provided for DHS employees and contractors under the Accessibility Compliance Management System.
