### ISSUE TITLE
2.4.3 Focus Order includes backward navigation

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#216]
Review [3. Focus Order](https://section508coordinators.github.io/ICTTestingBaseline/03FocusOrder.html) if any edit is needed.

**Comment by AnnMarieDavis** [comment]
Should there be an addition that forward and backward focus order should follow the same path?

**Comment by kengdoj** [comment]
@AnnMarieDavis , no that is not required. 

The example that helped clarify this for me:

> A listing of NBA standings or NHL standings where the teams are tab-able, and sequence of the teams has meaning: their position in the standings.  As one tabs through the teams, their position in the sequence is their ranking in the standings.  

Here, forward navigation through this list means the rank is getting worse (best to worst).  Backward navigation means their rank is getting better (worst to best). Each direction has a meaning.

If there is meaning for backwards navigation, then focus order must preserve the meaning. It  is not required that forward navigation sequence must reverse in the exact opposite sequence.

**Comment by AnnMarieDavis** [comment]
The ranking example would seem to require sequential tab order be maintained forwards and backwards. Either go from highest to lowest ranking in order, or in reverse order from lowest to highest ranking. Anything other than maintaining the same sequence would cause confusion and not preserve the meaning.

1. But what about if forward order is "lions, tigers, bears, oh my" . If I then reverse tab from "oh my" shouldn't I expect to go to "bears" rather than "tigers"? People often remember the general list order and if they reverse to get back to something would become confused if the order is not preserved. 

1. If I am entering an address and encounter a keyboard trap that creates a loop in city, state entries, I have a focus order issue because I cannot tab to the zip code. However is it also a focus order issue because I cannot reverse tab to the street address field from the city text box?

**Comment by cliffbert** [comment]
1. Seems confusing to me.
2. Seems confusing to me.

**Comment by bruce-usab** [comment]
> Should there be an addition that forward and backward focus order should follow the same path?

No.  The backwards focus order has to <q>preserves meaning and operability</q> but it might not mirror the forward focus order.

Your address example @AnnMarieDavis is one that clarifies this for me.  Forward focus order is almost certainly name, address line 1, address line 2, city, state, zip.  Backward focus could be the exact opposite **or** it might very well sensibly be:  zip, state, city, address line 1, name _with address line 2 skipped_.

Another example is a series of survey questions, each with a several choices for answers.  Forward tab order could be expected to go from a question through each of it several its answers.  Reverse tab from an answer could sensibly move focus back to the question, and reverse tab from a question move focus to the previous question (as opposed to moving focus to the last answer of the previous question.

**Comment by AnnMarieDavis** [comment]
Bruce,

Thanks for the clarification. We will look to provide notes to the next version of the test process to clarify this.

Kind Regards,
Ann Marie

Ann Marie Davis
Senior Section 508 Technical Specialist
DHS OAST
Phone #: 202-815-5428
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>
