### ISSUE TITLE
Outline numbering on HTML page

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#218]
The [.md page](https://github.com/Section508Coordinators/ICTTestingBaseline/blob/master/docs/03FocusOrder.md) outline levels appear correctly (1, i, a.).

On [.html page](https://section508coordinators.github.io/ICTTestingBaseline/03FocusOrder.html), the outlines are 1's and 2's.

**Comment by kengdoj** [comment]
From @drewnielson :

It is some function of the Jekyll engine that is rendering the nested lists differently than the native GitHub markdown conversion. I'll have to investigate a little more to figure out whether it is Jekyll, the particular Jekyll theme we are using, or something else. Might be able to implement a work-around by just using HTML for the lists.

**Comment by bruce-usab** [comment]
FWIW, I think it maybe that github.io rendering is using no CSS formatting.  The default HTML presentation for nested OL is that the inner lists use 1s and 2s, just like the default.

@drewnielson Can you specify style sheets with github.io?

**Comment by drewnielson** [comment]
Bruce, for the ICT Baseline repository/site, we’re actually using a feature
of GitHub that converts Markdown formatted files to HTML. It uses the
Jekyll engine to convert the md to html and adds an entire theme using css
and JavaScript. So on the authoring end it made it a lot easier for the
authors to edit the content in markdown, and then there was no effort
(aside from the Jekyll setup) to publish to the web as html. Something went
a little haywire in that conversion process. Either it has something to do
with our md formatting that prevented the Jekyll engine from recognizing
and applying the nested lists and hierarchical numbering, or it could be an
issue with the particular Jekyll theme we’re using, or it could be
something else. I have some ideas for a work-around even if I can’t find
the root cause, but even better if I can find the root cause.

**Comment by bruce-usab** [comment]
We are using Jekyll (via Federalist and USWDS) for our site migration.  I have not yet experimented with how it renders nested OLs.  I just wanted to be clear:  the Baseline pages are only written once, and that the source format is Markdown, correct?

**Comment by drewnielson** [comment]
Yep, correct: The baseline pages are only written once, and the source
files are written in Markdown.
